services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: new_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
      - "9080:9080"
    environment:
      - JENKINS_OPTS="--httpPort=9080"
    restart: always
    # command: /usr/local/bin/dependencies.sh
#     volumes:
#       - jenkins_home:/var/jenkins_home

# volumes:
#   jenkins_home:



